# Generated by Django 4.2.6 on 2023-10-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("productId", models.TextField()),
                ("productName", models.CharField(max_length=100)),
                ("productOwnerName", models.CharField(max_length=50)),
                ("developers", models.JSONField()),
                ("scrumMasterName", models.CharField(max_length=50)),
                ("startDate", models.DateField()),
                ("methodology", models.TextField()),
                ("location", models.TextField()),
            ],
        ),
    ]
